[build-system]
requires = [
  "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"


[project]
name = "implicitlab"
version = "0.1.1"
authors = [
  { name="Guillaume Coiffier" },
]
description = ""
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "tqdm",
  "numpy",
  "torch>=2.9.1",
  "mouette",
  "scikit-image",
  "scipy",
  "matplotlib",
  "meshio",
  "triangle",
  "libigl>=2.6.2",
  "deel-torchlip>=1.0.5",
]


[project.urls]
"Homepage" = "https://github.com/GCoiffier/neural_implicit_lab"
"Documentation" = "https://GCoiffier.github.io/neural_implicit_lab/"
