[build-system]
requires = [
  "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"


[project]
name = "implicitlab"
version = "0.1.1"
authors = [
  { name="Guillaume Coiffier" },
]
description = ""
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
"torch>=2.9.1",
"numpy",
"scipy",
"scikit-image",
"matplotlib",
"mouette==1.2.7.1",
"libigl>=2.6.1",
"triangle",
"tqdm",
"deel-torchlip>=1.0.5",
"meshio"
]


[project.urls]
"Homepage" = "https://github.com/GCoiffier/neural_implicit_lab"
"Documentation" = "https://GCoiffier.github.io/neural_implicit_lab/"
